"use client";

import Footer1 from "@/components/Footer1";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer2 from "@/components/Footer2";

// export const metadata = {
//   title: "PPID UHO",
//   description: "Generated by create next app",
// };
import { useEffect } from "react";
import Router from "next/router";
import NProgress from "nprogress"; // Import nprogress
import "nprogress/nprogress.css"; // Import styles for nprogress

export default function RootLayout({ children }) {
  NProgress.configure({ showSpinner: false });
  useEffect(() => {
    const start = () => NProgress.start();
    const done = () => NProgress.done();

    Router.events.on("routeChangeStart", start);
    Router.events.on("routeChangeComplete", done);
    Router.events.on("routeChangeError", done);

    return () => {
      Router.events.off("routeChangeStart", start);
      Router.events.off("routeChangeComplete", done);
      Router.events.off("routeChangeError", done);
    };
  }, []);

  return (
    <html lang="en">
      <head>
        <title>PPID UHO</title>
        <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
      </head>
      <body className={"font-poppins"}>
        <Navbar />
        {children}
        <Footer1 />
        <Footer2 />
      </body>
    </html>
  );
}
