import Footer1 from "@/components/Footer1";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer2 from "@/components/Footer2";

export const metadata = {
  title: "PPID UHO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>PPID UHO</title>
        <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
      </head>
      <body className={"font-poppins"}>
        <Navbar />
        {children}
        <Footer1 />
        <Footer2 />
      </body>
    </html>
  );
}
